version: "3.9"

services:
  prestashop_db:
    image: mysql:8.0
    container_name: prestashop_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    ports:
      - ${PORTAINER_DB_PORT}:3306
    networks:
      - prestashop_network
    volumes:
      - db_data:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    restart: always
    env_file:
      - .env
    ports:
      - ${PORTAINER_PRESTASHOP_PORT}:80
    networks:
      - prestashop_network
    depends_on:
      - prestashop_db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:

networks:
    prestashop_network:
